### ISSUE TITLE
install.sh enhancement

### ISSUE THREAD

**Issue by Lamecarlate** [vinceliuice/ChromeOS-theme#1]
Hello :)

My setup at home uses spaces in folder names (for example "02 - Informatique" for my computer stuff), and your `install.sh` failed with that. I tinkered with it and succeeded to install!

So I would like to share my enhancement - I'll post here because I don't want to go through the whole fork thing for five lines, I hope you'll forgive me.

Lines 77 to 81 were touched.

```
mkdir -p                                                                                "${THEME_DIR}/gnome-shell"
cp -ur "${SRC_DIR}"/gnome-shell/{extensions,message-indicator-symbolic.svg,pad-osd.css} "${THEME_DIR}/gnome-shell"
cp -ur "${SRC_DIR}/gnome-shell/gnome-shell$color$size.css"                              "${THEME_DIR}/gnome-shell/gnome-shell.css"
cp -ur "${SRC_DIR}/gnome-shell/common-assets"                                           "${THEME_DIR}/gnome-shell/assets"
cp -ur "${SRC_DIR}"/gnome-shell/assets${ELSE_DARK:-}/*.svg                              "${THEME_DIR}/gnome-shell/assets"
```

Cheers!

**Comment by vinceliuice** [comment]
Thanks! I'll fix this

**Comment by vinceliuice** [comment]
Fixed!

**Comment by Lamecarlate** [comment]
Thanks for your reactivity! (I think most of your other themes `install.sh` will have the same issue, embedding `${SRC_DIR}` with quotes should be enough.)

**Comment by vinceliuice** [comment]
You are right! I'll check and fixed it!
