### ISSUE TITLE
not all apps have multicolor gtkheaderbar in gtk 3.26 or gtk 3.28

### ISSUE THREAD

**Issue by denikris** [vinceliuice/ChromeOS-theme#11]
ubuntu-budgie 18.04 lts
budgie-desktop 10.5 (from backport ppa)
![Screenshot from 2020-02-03 20-01-50](https://user-images.githubusercontent.com/16707606/73655920-a50dd100-46c1-11ea-9bed-aa69e6221ebe.png)

some apps like **budgie desktop settings**, **gnome system monitor**, **gnome calendar** and **google chrome (chromium)** have dynamic colors like grey/green/purple but some apps like **file-roller**, **gnome-calculator** and **gedit** have default blue like nautilus and non-csd apps

they are in version 3.28

**Comment by vinceliuice** [comment]
Because not all app support multicolor headerbar, I also want all app have multicolor headerbar but only after these software support。
