### ISSUE TITLE
gnome-shell notification display issue

### ISSUE THREAD

**Issue by yjzzjy4** [vinceliuice/ChromeOS-theme#17]
**First of all, I really love your great work, thx!!!**
But unfortunately there is still some slightly issues after your last update in Apr.
Most of the problems are the **pop-up notifications' display style** and the **in-panel notifications' display style**, like the picture below:
![image](https://user-images.githubusercontent.com/43295657/79295241-cd5c4c00-7f0a-11ea-8beb-4066b2e6a871.png)

**There should be text under the title of the notification, but now can only been seen after your mouse cursor is hovered over them (yes, my cursor are hoverd, somehow the screenshot didn't get that:smile:)**, like this:
![image](https://user-images.githubusercontent.com/43295657/79295267-de0cc200-7f0a-11ea-962c-c9c94092293b.png)

And the same happened after the notifications were in-panel area, like this:
![image](https://user-images.githubusercontent.com/43295657/79295327-f977cd00-7f0a-11ea-9b0d-9394bc61ea8c.png)

And when I put the cursor over it, the text showed up, but barely to be seen, like this:
![image](https://user-images.githubusercontent.com/43295657/79295732-06e18700-7f0c-11ea-857a-5ef84834a896.png)

The other areas look just fine to me, only the pop-up notifications and the panel notifications, here is what the other areas look like:
![image](https://user-images.githubusercontent.com/43295657/79295411-2c21c580-7f0b-11ea-8207-9cdae23cee7c.png)
![image](https://user-images.githubusercontent.com/43295657/79295433-3ba10e80-7f0b-11ea-88e6-2ac8e4296a0a.png)
![image](https://user-images.githubusercontent.com/43295657/79295459-4e1b4800-7f0b-11ea-8135-0d3256cf7eb2.png)

I guess the gnome-3.36 is to blame, caz the other of my device runs Ubuntu 18.04 with gnome-3.34 doesn't encounter the same issue here (No problem at all).

BTW, I'm currently in Ubuntu 20.04 with gnome-3.36.

**Thanks again for your decent work, looking foward to see the update!!!**

**Comment by vinceliuice** [comment]
Thanks! I'll fix it
