### ISSUE TITLE
How to change the background of selected text?

### ISSUE THREAD

**Issue by ywxt** [vinceliuice/ChromeOS-theme#2]
I want to change the background of selected text. How to do?

Thanks.

**Comment by vinceliuice** [comment]
需要修改源代码

**Comment by vinceliuice** [comment]
下次更新的时候我会修复这个的

**Comment by ywxt** [comment]
> 需要修改源代码

我找到修改的地方了，之前一直在查找颜色值，后来看了一下源码，原来用的是rgba。

**Comment by vinceliuice** [comment]
好的

**Comment by mauriziopinotti** [comment]
hi @vinceliuice , @ywxt, what is the CSS selector to change to achieve this?

**Comment by ywxt** [comment]
> hi @vinceliuice , @ywxt, what is the CSS selector to change to achieve this?

Sorry, I almost forgot it. Maybe you can search `background-color: rgba(0, 0, 0, 0.0` in gtk.css.
