### ISSUE TITLE
Firefox URL bar broken in Firefox 77.0.1

### ISSUE THREAD

**Issue by OnTes** [vinceliuice/ChromeOS-theme#20]
Firefox search suggestions are messed up on the latest version of Firefox.
Version 77.0 is working as expected (which is strange because 77.0.1 should be only a bugfix).
I'm running Gnome on PopOS 20.4.

Anyways thanks for the theme, your themes are absolutely the best!

**Comment by AxelSally2** [comment]
Same here (Also on PopOS 20.04)
I was about to make an issue too

**Comment by DrackNife** [comment]
Same on Linux Mint 19.3

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed!
