### ISSUE TITLE
Hard to see colors in title bar

### ISSUE THREAD

**Issue by reC0D3D** [vinceliuice/ChromeOS-theme#25]
I've been really enjoying this theme. It's a streamlined and modern Materia, which was my previous go-to theme. I noticed a few issues regarding colors in the title bar. 

Because the title bar is the same color as some of the other elements of the system, it makes certain things appear invisible, such as highlighted text.

![Default theme](https://user-images.githubusercontent.com/29968331/95500179-4fc64580-095b-11eb-8513-c57c3d536154.png)
_This is the default ChromeOS theme_.

![Light theme](https://user-images.githubusercontent.com/29968331/95500210-59e84400-095b-11eb-98e6-28a9534de90d.png)
_This is the ChromeOS-light theme._

As someone who saves documents all the time, this is a major flaw of the default ChromeOS theme. I'm not entirely sure how this would be fixed. Perhaps a lighter or darker version of the title bar color could be used instead? 

Another area where I saw this issue was when a switch is in the title bar. This can be seen in a few areas, such as the GNOME settings and extensions applications.

![Extensions app](https://user-images.githubusercontent.com/29968331/95500705-0e826580-095c-11eb-89a5-f622e9258db0.png)
_This is using the default ChromeOS theme. As you can see, the switch doesn't use the same color, but it is a very similar shade of blue._

An easy fix for this would be to color the switches in the title bar white. This is what Google does on both Android and ChromeOS to circumvent this issue.

I hope these issues can be looked at and solved. I really enjoy using the default variant of this theme, but these minor issues hold me back.

**Comment by vinceliuice** [comment]
I'll fix this!
