### ISSUE TITLE
Secondary text in notifications is black-on-black

### ISSUE THREAD

**Issue by techmagus** [vinceliuice/ChromeOS-theme#28]
Hi,

The secondary text in notifications is showing as black-on-black. If you don't hover on the notifications, the secondary is not visible.

Here are some screenshots:

![Screenshot from 2021-01-08 08-18-40](https://user-images.githubusercontent.com/1079205/103960389-04574980-518d-11eb-9759-348e26595c97.png)
![Screenshot from 2021-01-08 08-18-58](https://user-images.githubusercontent.com/1079205/103960393-05887680-518d-11eb-9c88-4033aba33977.png)
![Screenshot from 2021-01-08 08-20-42](https://user-images.githubusercontent.com/1079205/103960394-06210d00-518d-11eb-81db-7023c48964de.png)

In this particular notification, when you hover on it the text switches to white-on-black.
![Screenshot from 2021-01-08 08-20-58](https://user-images.githubusercontent.com/1079205/103960395-06b9a380-518d-11eb-94b7-80d4c876dc03.png)
![Screenshot from 2021-01-08 08-21-00](https://user-images.githubusercontent.com/1079205/103960397-07523a00-518d-11eb-80be-02a4f650e6e4.png)

Other information:
* Ubuntu 20.04 LTS
* Gnome-shell theme installed via: https://www.opendesktop.org/p/1333760/
* Gnome-shell version: 3.36.4

Shalom!

**Comment by vinceliuice** [comment]
Please install this theme from here, i did not update on opendesktop

**Comment by techmagus** [comment]
> Please install this theme from here, i did not update on opendesktop

Alright, thank you for the update.

Shalom!
