### ISSUE TITLE
Dark mode is the clone of materia dark, colorful headers disappeared

### ISSUE THREAD

**Issue by ceyhunn** [vinceliuice/ChromeOS-theme#3]

**Comment by vinceliuice** [comment]
I'll fixed this

**Comment by gsbhasin123** [comment]
Fixed now?

**Comment by vinceliuice** [comment]
Yes, fixed

**Comment by gsbhasin123** [comment]
Nice @vinceliuice 
Also, can your themes have plugins in the Oomox software?  https://github.com/themix-project/oomox
i made my own theme, https://gitlab.com/Gsbhasin84/materiav2, and would love to make spins on it using Qogir, Vimix, and Canta bases. thx

**Comment by vinceliuice** [comment]
OK! I'll consider that

**Comment by gsbhasin123** [comment]
Ok thanks always wanted this!see https://github.com/themix-project/oomox/tree/master/plugins/theme_materia as an example.

> OK! I'll consider that

**Comment by gsbhasin123** [comment]
Also close this issue

**Comment by ceyhunn** [comment]
Hi @vinceliuice , I tested, but only nautilus doesn't show  blue header color.

**Comment by gsbhasin123** [comment]
Yes indeed.
Mutter windows should also @vinceliuice... thx
Like from the Mutter window manager
The color should change
like apps that use headerbar

**Comment by ceyhunn** [comment]
I tested, this issue fixed.
