### ISSUE TITLE
budgie panel fix

### ISSUE THREAD

**Issue by gsbhasin123** [vinceliuice/ChromeOS-theme#5]
here:
![image](https://user-images.githubusercontent.com/48339289/70383608-5f34c680-1925-11ea-835a-2e1433d289aa.png)

The circles should not be around the app icons.
Same occurs with non transparent panel. Pls fix asap.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by gsbhasin123** [comment]
thanks a lot :) fixed
Now all I need is an Oomox theme :P
