### ISSUE TITLE
budgie indicator lock key unreadable in dark and compact dark theme

### ISSUE THREAD

**Issue by denikris** [vinceliuice/ChromeOS-theme#9]
ubuntu budgie 19.10
budgie desktop 10.5

this is light and standart version

![Screenshot from 2020-01-23 09-35-02](https://user-images.githubusercontent.com/16707606/72952191-ac7cd280-3dc3-11ea-8d56-127168e0f9c2.png)
this is when caps lock and num lock is off

![Screenshot from 2020-01-23 09-38-36](https://user-images.githubusercontent.com/16707606/72952354-3036bf00-3dc4-11ea-9a2a-2e7bf2a0bb6f.png)
this is when caps lock on but num lock off

![Screenshot from 2020-01-23 09-40-08](https://user-images.githubusercontent.com/16707606/72952417-607e5d80-3dc4-11ea-9870-03959aed3827.png)
in dark version, those 2 have same color either is on or off

**Comment by denikris** [comment]
dynamic transparent is on btw, it still same when window maximized or unmaximized

**Comment by vinceliuice** [comment]
I fixed this issue, you can download the last update here
